name: admin
description: A flutter dashboard mock for web.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  google_fonts: ^2.0.0
  flutter_svg: ^0.22.0
  fl_chart: ^0.35.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/Documents.svg
    - assets/icons/Figma_file.svg
    - assets/icons/Search.svg
    - assets/icons/doc_file.svg
    - assets/icons/drop_box.svg
    - assets/icons/excle_file.svg
    - assets/icons/folder.svg
    - assets/icons/google_drive.svg
    - assets/icons/logo.svg
    - assets/icons/media.svg
    - assets/icons/media_file.svg
    - assets/icons/menu_dashbord.svg
    - assets/icons/menu_doc.svg
    - assets/icons/menu_notification.svg
    - assets/icons/menu_profile.svg
    - assets/icons/menu_setting.svg
    - assets/icons/menu_store.svg
    - assets/icons/menu_task.svg
    - assets/icons/menu_tran.svg
    - assets/icons/one_drive.svg
    - assets/icons/pdf_file.svg
    - assets/icons/sound_file.svg
    - assets/icons/unknown.svg
    - assets/icons/xd_file.svg
    - assets/images/logo.png
    - assets/images/profile_pic.png

