name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: |
          flutter build web --release
          mv build/web docs
      - name: Commit and push build
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'build: update build'
          add: 'docs/*'
      - name: Replace base href
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<base href=\"/\">"
          replace: "<base href=\"./\">"
          include: docs/index.html
